from google.cloud import bigquery
from google.oauth2 import service_account

# Replace with the path to your service account key file
key_path = 'wmt-cc-datasphere-dev-df.json'

# Create a credentials object from the key file
credentials = service_account.Credentials.from_service_account_file(key_path)

# Create a BigQuery client with the project and credentials
client = bigquery.Client(project='wmt-cc-datasphere-prod', credentials=credentials)

# Create the table
table_id = 'wmt-cc-datasphere-prod.cisco_cdr.cisco-cdr-raw-data'
schema = [
    bigquery.SchemaField('cdrRecordType', 'INTEGER'), bigquery.SchemaField('globalCallID_callManagerId', 'INTEGER'),
    bigquery.SchemaField('globalCallID_callId', 'INTEGER'), bigquery.SchemaField('origLegCallIdentifier', 'INTEGER'),
    bigquery.SchemaField('dateTimeOrigination', 'INTEGER'), bigquery.SchemaField('origNodeId', 'INTEGER'),
    bigquery.SchemaField('origSpan', 'INTEGER'), bigquery.SchemaField('origIpAddr', 'INTEGER'),
    bigquery.SchemaField('callingPartyNumber', 'STRING'),
    bigquery.SchemaField('callingPartyUnicodeLoginUserID', 'STRING'),
    bigquery.SchemaField('origCause_location', 'INTEGER'), bigquery.SchemaField('origCause_value', 'INTEGER'),
    bigquery.SchemaField('origPrecedenceLevel', 'INTEGER'),
    bigquery.SchemaField('origMediaTransportAddress_IP', 'INTEGER'),
    bigquery.SchemaField('origMediaTransportAddress_Port', 'INTEGER'),
    bigquery.SchemaField('origMediaCap_payloadCapability', 'INTEGER'),
    bigquery.SchemaField('origMediaCap_maxFramesPerPacket', 'INTEGER'),
    bigquery.SchemaField('origMediaCap_g723BitRate', 'INTEGER'), bigquery.SchemaField('origVideoCap_Codec', 'INTEGER'),
    bigquery.SchemaField('origVideoCap_Bandwidth', 'INTEGER'),
    bigquery.SchemaField('origVideoCap_Resolution', 'INTEGER'),
    bigquery.SchemaField('origVideoTransportAddress_IP', 'INTEGER'),
    bigquery.SchemaField('origVideoTransportAddress_Port', 'INTEGER'),
    bigquery.SchemaField('origRSVPAudioStat', 'STRING'), bigquery.SchemaField('origRSVPVideoStat', 'STRING'),
    bigquery.SchemaField('destLegIdentifier', 'INTEGER'), bigquery.SchemaField('destNodeId', 'INTEGER'),
    bigquery.SchemaField('destSpan', 'INTEGER'), bigquery.SchemaField('destIpAddr', 'INTEGER'),
    bigquery.SchemaField('originalCalledPartyNumber', 'STRING'),
    bigquery.SchemaField('finalCalledPartyNumber', 'STRING'),
    bigquery.SchemaField('finalCalledPartyUnicodeLoginUserID', 'STRING'),
    bigquery.SchemaField('destCause_location', 'INTEGER'), bigquery.SchemaField('destCause_value', 'INTEGER'),
    bigquery.SchemaField('destPrecedenceLevel', 'INTEGER'),
    bigquery.SchemaField('destMediaTransportAddress_IP', 'INTEGER'),
    bigquery.SchemaField('destMediaTransportAddress_Port', 'INTEGER'),
    bigquery.SchemaField('destMediaCap_payloadCapability', 'INTEGER'),
    bigquery.SchemaField('destMediaCap_maxFramesPerPacket', 'INTEGER'),
    bigquery.SchemaField('destMediaCap_g723BitRate', 'INTEGER'), bigquery.SchemaField('destVideoCap_Codec', 'INTEGER'),
    bigquery.SchemaField('destVideoCap_Bandwidth', 'INTEGER'),
    bigquery.SchemaField('destVideoCap_Resolution', 'INTEGER'),
    bigquery.SchemaField('destVideoTransportAddress_IP', 'INTEGER'),
    bigquery.SchemaField('destVideoTransportAddress_Port', 'INTEGER'),
    bigquery.SchemaField('destRSVPAudioStat', 'STRING'), bigquery.SchemaField('destRSVPVideoStat', 'STRING'),
    bigquery.SchemaField('dateTimeConnect', 'INTEGER'), bigquery.SchemaField('dateTimeDisconnect', 'INTEGER'),
    bigquery.SchemaField('lastRedirectDn', 'STRING'), bigquery.SchemaField('pkid', 'STRING'),
    bigquery.SchemaField('originalCalledPartyNumberPartition', 'STRING'),
    bigquery.SchemaField('callingPartyNumberPartition', 'STRING'),
    bigquery.SchemaField('finalCalledPartyNumberPartition', 'STRING'),
    bigquery.SchemaField('lastRedirectDnPartition', 'STRING'), bigquery.SchemaField('duration', 'INTEGER'),
    bigquery.SchemaField('origDeviceName', 'STRING'), bigquery.SchemaField('destDeviceName', 'STRING'),
    bigquery.SchemaField('origCallTerminationOnBehalfOf', 'INTEGER'),
    bigquery.SchemaField('destCallTerminationOnBehalfOf', 'INTEGER'),
    bigquery.SchemaField('origCalledPartyRedirectOnBehalfOf', 'INTEGER'),
    bigquery.SchemaField('lastRedirectRedirectOnBehalfOf', 'INTEGER'),
    bigquery.SchemaField('origCalledPartyRedirectReason', 'INTEGER'),
    bigquery.SchemaField('lastRedirectRedirectReason', 'INTEGER'),
    bigquery.SchemaField('destConversationId', 'INTEGER'), bigquery.SchemaField('globalCallId_ClusterID', 'STRING'),
    bigquery.SchemaField('joinOnBehalfOf', 'INTEGER'), bigquery.SchemaField('comment', 'STRING'),
    bigquery.SchemaField('authCodeDescription', 'STRING'), bigquery.SchemaField('authorizationLevel', 'INTEGER'),
    bigquery.SchemaField('clientMatterCode', 'STRING'), bigquery.SchemaField('origDTMFMethod', 'INTEGER'),
    bigquery.SchemaField('destDTMFMethod', 'INTEGER'), bigquery.SchemaField('callSecuredStatus', 'INTEGER'),
    bigquery.SchemaField('origConversationId', 'INTEGER'), bigquery.SchemaField('origMediaCap_Bandwidth', 'INTEGER'),
    bigquery.SchemaField('destMediaCap_Bandwidth', 'INTEGER'), bigquery.SchemaField('authorizationCodeValue', 'STRING'),
    bigquery.SchemaField('outpulsedCallingPartyNumber', 'STRING'),
    bigquery.SchemaField('outpulsedCalledPartyNumber', 'STRING'), bigquery.SchemaField('origIpv4v6Addr', 'STRING'),
    bigquery.SchemaField('destIpv4v6Addr', 'STRING'), bigquery.SchemaField('origVideoCap_Codec_Channel2', 'INTEGER'),
    bigquery.SchemaField('origVideoCap_Bandwidth_Channel2', 'INTEGER'),
    bigquery.SchemaField('origVideoCap_Resolution_Channel2', 'INTEGER'),
    bigquery.SchemaField('origVideoTransportAddress_IP_Channel2', 'INTEGER'),
    bigquery.SchemaField('origVideoTransportAddress_Port_Channel2', 'INTEGER'),
    bigquery.SchemaField('origVideoChannel_Role_Channel2', 'INTEGER'),
    bigquery.SchemaField('destVideoCap_Codec_Channel2', 'INTEGER'),
    bigquery.SchemaField('destVideoCap_Bandwidth_Channel2', 'INTEGER'),
    bigquery.SchemaField('destVideoCap_Resolution_Channel2', 'INTEGER'),
    bigquery.SchemaField('destVideoTransportAddress_IP_Channel2', 'INTEGER'),
    bigquery.SchemaField('destVideoTransportAddress_Port_Channel2', 'INTEGER'),
    bigquery.SchemaField('destVideoChannel_Role_Channel2', 'INTEGER'),
    bigquery.SchemaField('IncomingProtocolID', 'INTEGER'), bigquery.SchemaField('IncomingProtocolCallRef', 'STRING'),
    bigquery.SchemaField('OutgoingProtocolID', 'INTEGER'), bigquery.SchemaField('OutgoingProtocolCallRef', 'STRING'),
    bigquery.SchemaField('currentRoutingReason', 'INTEGER'), bigquery.SchemaField('origRoutingReason', 'INTEGER'),
    bigquery.SchemaField('lastRedirectingRoutingReason', 'INTEGER'),
    bigquery.SchemaField('huntPilotPartition', 'STRING'), bigquery.SchemaField('huntPilotDN', 'STRING'),
    bigquery.SchemaField('calledPartyPatternUsage', 'INTEGER'), bigquery.SchemaField('IncomingICID', 'STRING'),
    bigquery.SchemaField('IncomingOrigIOI', 'STRING'), bigquery.SchemaField('IncomingTermIOI', 'STRING'),
    bigquery.SchemaField('OutgoingICID', 'STRING'), bigquery.SchemaField('OutgoingOrigIOI', 'STRING'),
    bigquery.SchemaField('OutgoingTermIOI', 'STRING'),
    bigquery.SchemaField('outpulsedOriginalCalledPartyNumber', 'STRING'),
    bigquery.SchemaField('outpulsedLastRedirectingNumber', 'STRING'), bigquery.SchemaField('wasCallQueued', 'INTEGER'),
    bigquery.SchemaField('totalWaitTimeInQueue', 'INTEGER'), bigquery.SchemaField('callingPartyNumber_uri', 'STRING'),
    bigquery.SchemaField('originalCalledPartyNumber_uri', 'STRING'),
    bigquery.SchemaField('finalCalledPartyNumber_uri', 'STRING'), bigquery.SchemaField('lastRedirectDn_uri', 'STRING'),
    bigquery.SchemaField('mobileCallingPartyNumber', 'STRING'),
    bigquery.SchemaField('finalMobileCalledPartyNumber', 'STRING'),
    bigquery.SchemaField('origMobileDeviceName', 'STRING'), bigquery.SchemaField('destMobileDeviceName', 'STRING'),
    bigquery.SchemaField('origMobileCallDuration', 'INTEGER'),
    bigquery.SchemaField('destMobileCallDuration', 'INTEGER'), bigquery.SchemaField('mobileCallType', 'INTEGER'),
    bigquery.SchemaField('originalCalledPartyPattern', 'STRING'),
    bigquery.SchemaField('finalCalledPartyPattern', 'STRING'),
    bigquery.SchemaField('lastRedirectingPartyPattern', 'STRING'), bigquery.SchemaField('huntPilotPattern', 'STRING'),
    bigquery.SchemaField('origDeviceType', 'STRING'), bigquery.SchemaField('destDeviceType', 'STRING'),
    bigquery.SchemaField('origDeviceSessionID', 'STRING'), bigquery.SchemaField('destDeviceSessionID', 'STRING')
]
table = bigquery.Table(table_id, schema=schema)
table = client.create_table(table)  # Make an API request.
